# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - isa2-imetrix-api-admin-qa

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://isa2container.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_69235e0518a54321a1a47be1157dfed0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3b52b2e9624342e496ed60cfa08faf65 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: isa2container.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_69235e0518a54321a1a47be1157dfed0 }}/api-admin:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'isa2-imetrix-api-admin-qa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_76af100021d94f6099003a295a57b987 }}
        images: 'isa2container.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_69235e0518a54321a1a47be1157dfed0 }}/api-admin:${{ github.sha }}'